# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://beunstuck.github.io
title: Unstuck scheduling
email: your-email@domain.com
author: Your Name
description: ""
copyright: 'Copyright &copy; 2021 Unstuck. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: listings
    url: https://booking.beunstuck.net/listings
    button_icon: 'users'
  - title: sign up
    url: https://dashboard.beunstuck.net/signup/1
    button_icon: 'plus-circle'
  - title: sign in
    url: https://dashboard.beunstuck.net/login
    button_icon: 'sign-in'

